var events = [

  {'Date': new Date(2016, 11, 7), 'Title':' <font color=green><b>TITLE</b></font>: Workshop on "Big Data" <br><font color=green><b>TIME</b></font>: 3:00 PM, <br><font color=green><b>VENU</b></font>: A1 NKN.'},

  {'Date': new Date(2016, 11, 18), 'Title': '<font color=green><b>TITLE</b></font>: Workshop on "Pahari Painting", <br><font color=green><b>TIME</font></b>: 1:00 PM, <br><font color=green><b>VENU</font></b>: D1 Lounge', 'Link': 'http://www.iitmandi.ac.in/news/articles/2nd_Pahari%20Painting%20Workshop.pdf'},

  {'Date': new Date(2017, 1, 7), 'Title': 'Workshop on Bioengineering measures <br>to control landslides and geoenvironmental issue <br>7th to 9th Feb 2017', 'Link': 'http://iitmandi.ac.in/MyWebPage/home/news/articles/bioengg_landslide_workshop2017.pdf'},

  {'Date': new Date(2017, 1, 13), 'Title': 'Book Fair on 13th and 14th Feb 2017,<br>VENU A5 Building, TIME 09:00 AM to 06:00 PM', 'Link': 'http://iitmandi.ac.in/MyWebPage/home/news/articles/Bookfair_2017.pdf'},
  
  
  {'Date': new Date(2017, 1, 17), 'Title': 'Design and Innovation <br>Centre inauguration, TIME:04:00 PM'},

  {'Date': new Date(2017, 1, 24), 'Title': '8th Foundation Day of IIT Mandi'},

  {'Date': new Date(2017, 2, 6), 'Title': 'Workshop on<br><font color=green><b>TITLE:</b></font>  "Tackling Development Challenges in Himalayan Region <br>through Internet of Things (IoT) Enabled Services and Devices",<br><font color=green><b>VENU</b></font> - A1 NKN, <font color=green><b>TIME</b></font> - 09:00 AM to 05:00 PM', 'Link': 'http://iitmandi.ac.in/iot_mandi'},

{'Date': new Date(2017, 2, 14), 'Title': 'Quiz 1', 'Link': '../academics/files/acad_calendar2016-17.pdf'},
{'Date': new Date(2017, 2, 15), 'Title': 'Quiz 2', 'Link': '../academics/files/acad_calendar2016-17.pdf'},
{'Date': new Date(2017, 2, 16), 'Title': 'Quiz 3', 'Link': '../academics/files/acad_calendar2016-17.pdf'},
{'Date': new Date(2017, 2, 17), 'Title': 'Quiz 4', 'Link': '../academics/files/acad_calendar2016-17.pdf'},
{'Date': new Date(2017, 2, 20), 'Title': 'Quiz 5', 'Link': '../academics/files/acad_calendar2016-17.pdf'},
{'Date': new Date(2017, 2, 21), 'Title': 'Quiz 6', 'Link': '../academics/files/acad_calendar2016-17.pdf'},
{'Date': new Date(2017, 2, 22), 'Title': 'Quiz 7', 'Link': '../academics/files/acad_calendar2016-17.pdf'},
{'Date': new Date(2017, 2, 23), 'Title': 'Quiz 8', 'Link': '../academics/files/acad_calendar2016-17.pdf'},
{'Date': new Date(2017, 2, 25), 'Title': 'Lit Fest', 'Link': '#'},
{'Date': new Date(2017, 2, 26), 'Title': 'Lit Fest', 'Link': '#'},


{'Date': new Date(2017, 3, 7), 'Title': 'Exodia', 'Link': '#'},
{'Date': new Date(2017, 3, 8), 'Title': 'Exodia', 'Link': '#'},
{'Date': new Date(2017, 3, 9), 'Title': 'Exodia', 'Link': '#'},
{'Date': new Date(2017, 3, 10), 'Title': 'CCM Week', 'Link': '#'},
{'Date': new Date(2017, 3, 14), 'Title': 'Rann', 'Link': '#'},
{'Date': new Date(2017, 3, 15), 'Title': 'Rann', 'Link': '#'},
{'Date': new Date(2017, 3, 20), 'Title': 'Quiz 1', 'Link': '../academics/files/acad_calendar2016-17.pdf'},
{'Date': new Date(2017, 3, 21), 'Title': 'Quiz 2', 'Link': '../academics/files/acad_calendar2016-17.pdf'},
{'Date': new Date(2017, 3, 24), 'Title': 'Quiz 3', 'Link': '../academics/files/acad_calendar2016-17.pdf'},
{'Date': new Date(2017, 3, 25), 'Title': 'Quiz 4', 'Link': '../academics/files/acad_calendar2016-17.pdf'},
{'Date': new Date(2017, 3, 26), 'Title': 'Quiz 5', 'Link': '../academics/files/acad_calendar2016-17.pdf'},
{'Date': new Date(2017, 3, 27), 'Title': 'Quiz 6', 'Link': '../academics/files/acad_calendar2016-17.pdf'},
{'Date': new Date(2017, 3, 28), 'Title': 'Quiz 7', 'Link': '../academics/files/acad_calendar2016-17.pdf'},

{'Date': new Date(2017, 4, 1), 'Title': 'Quiz 8', 'Link': '../academics/files/acad_calendar2016-17.pdf'},
{'Date': new Date(2017, 4, 6), 'Title': 'Aagaaz', 'Link': '../academics/files/acad_calendar2016-17.pdf'},
{'Date': new Date(2017, 4, 7), 'Title': 'Aagaaz', 'Link': '../academics/files/acad_calendar2016-17.pdf'},
{'Date': new Date(2017, 4, 20), 'Title': 'Aavishkar Open House/ISTP Open House', 'Link': '#'},
{'Date': new Date(2017, 4, 21), 'Title': 'DP Open House', 'Link': '#'},
{'Date': new Date(2017, 4, 27), 'Title': 'Hostel Night (Closing Ceremony of Hostel GC)', 'Link': '#'},


{'Date': new Date(2017, 5, 8), 'Title': 'National workshop on <br><font color=green><b>TITLE:</b></font> "A Multi Dimensional Smart Energy <br>Grid Analysis for Indian Scenario",<br><font color=green><b>DATES: </b></font> 8th to 10th June', 'Link': 'http://iitmandi.ac.in/mdeg'},
{'Date': new Date(2017, 5, 13), 'Title': 'Final CCM', 'Link': '#'},
{'Date': new Date(2017, 5, 14), 'Title': 'Grade Submission', 'Link': '#'},
{'Date': new Date(2017, 5, 17), 'Title': 'Third Workshop on <br><font color=green><b>TITLE:</b></font> "Machine Learning for Medical Image Analysis (WMLMIA 2017)",<br><font color=green><b>DATES: </b></font> 17th to 21th June', 'Link': 'http://iitmandi.ac.in/mdeg'},


{'Date': new Date(2017, 7, 1), 'Title': 'Reporting Day for 1st year B.Tech Students', 'Link': '#'},
{'Date': new Date(2017, 7, 9), 'Title': 'Classes Begin:Students Report to FA for Registration', 'Link': '#'},
{'Date': new Date(2017, 7, 18), 'Title': 'Last Date to add courses', 'Link': '#'},
{'Date': new Date(2017, 7, 19), 'Title': 'Aakarshan', 'Link': '#'},
{'Date': new Date(2017, 7, 25), 'Title': 'Last Date to Drop Courses', 'Link': '#'},
{'Date': new Date(2017, 7, 26), 'Title': 'Aagaman', 'Link': '#'},
{'Date': new Date(2017, 7, 28), 'Title': 'CCM Week', 'Link': '#'},

{'Date': new Date(2017, 8, 4), 'Title': 'Quiz 1', 'Link': 'http://www.iitmandi.ac.in/academics/files/Calender_Odd_2017.pdf'},
{'Date': new Date(2017, 8, 5), 'Title': 'Quiz 2', 'Link': 'http://www.iitmandi.ac.in/academics/files/Calender_Odd_2017.pdf'},
{'Date': new Date(2017, 8, 6), 'Title': 'Quiz 3', 'Link': 'http://www.iitmandi.ac.in/academics/files/Calender_Odd_2017.pdf'},
{'Date': new Date(2017, 8, 7), 'Title': 'Quiz 4', 'Link': 'http://www.iitmandi.ac.in/academics/files/Calender_Odd_2017.pdf'},
{'Date': new Date(2017, 8, 8), 'Title': 'Quiz 5', 'Link': 'http://www.iitmandi.ac.in/academics/files/Calender_Odd_2017.pdf'},
{'Date': new Date(2017, 8, 11), 'Title': 'Quiz 6', 'Link': 'http://www.iitmandi.ac.in/academics/files/Calender_Odd_2017.pdf'},
{'Date': new Date(2017, 8, 12), 'Title': 'Quiz 7', 'Link': 'http://www.iitmandi.ac.in/academics/files/Calender_Odd_2017.pdf'},
{'Date': new Date(2017, 8, 13), 'Title': 'Quiz 8', 'Link': 'http://www.iitmandi.ac.in/academics/files/Calender_Odd_2017.pdf'},
{'Date': new Date(2017, 8, 15), 'Title': 'Rann-Neeti(No Instruction Day)', 'Link': '#'},
{'Date': new Date(2017, 8, 16), 'Title': 'Rann-Neeti', 'Link': '#'},
{'Date': new Date(2017, 8, 17), 'Title': 'Rann-Neeti', 'Link': '#'},

{'Date': new Date(2017, 9, 3), 'Title': 'CCM Week', 'Link': '#'},
{'Date': new Date(2017, 9, 6), 'Title': 'Vibgyor', 'Link': '#'},
{'Date': new Date(2017, 9, 7), 'Title': 'Vibgyor', 'Link': '#'},
{'Date': new Date(2017, 9, 8), 'Title': 'Vibgyor', 'Link': '#'},
{'Date': new Date(2017, 9, 10), 'Title': 'Quiz 1', 'Link': 'http://www.iitmandi.ac.in/academics/files/Calender_Odd_2017.pdf'},
{'Date': new Date(2017, 9, 11), 'Title': 'Quiz 2', 'Link': 'http://www.iitmandi.ac.in/academics/files/Calender_Odd_2017.pdf'},
{'Date': new Date(2017, 9, 12), 'Title': 'Quiz 3', 'Link': 'http://www.iitmandi.ac.in/academics/files/Calender_Odd_2017.pdf'},
{'Date': new Date(2017, 9, 13), 'Title': 'Quiz 4', 'Link': 'http://www.iitmandi.ac.in/academics/files/Calender_Odd_2017.pdf'},
{'Date': new Date(2017, 9, 16), 'Title': 'Quiz 5', 'Link': 'http://www.iitmandi.ac.in/academics/files/Calender_Odd_2017.pdf'},
{'Date': new Date(2017, 9, 17), 'Title': 'Quiz 6', 'Link': 'http://www.iitmandi.ac.in/academics/files/Calender_Odd_2017.pdf'},
{'Date': new Date(2017, 9, 18), 'Title': 'Quiz 7', 'Link': 'http://www.iitmandi.ac.in/academics/files/Calender_Odd_2017.pdf'},
{'Date': new Date(2017, 9, 20), 'Title': 'Quiz 8', 'Link': 'http://www.iitmandi.ac.in/academics/files/Calender_Odd_2017.pdf'},

{'Date': new Date(2017, 10, 4), 'Title': 'Athletics Day', 'Link': '#'},
{'Date': new Date(2017, 10, 11), 'Title': 'Utkarsh', 'Link': '#'},
{'Date': new Date(2017, 10, 12), 'Title': 'Utkarsh', 'Link': '#'},
{'Date': new Date(2017, 10, 13), 'Title': 'TCF Week', 'Link': '#'},
{'Date': new Date(2017, 10, 20), 'Title': 'Last Day of Teaching (Except for B.Tech 1st year)', 'Link': '#'},


{'Date': new Date(2017, 11, 1), 'Title': 'Last Day of teaching for B.Tech. 1st year', 'Link': '#'},
{'Date': new Date(2017, 11, 4), 'Title': 'Mini Mathematics Training and Talent Search (Mini-MTTS) Programme', 'Link': '#'},

{'Date': new Date(2017, 11, 16), 'Title': 'National conference on <br><font color=green><b>TITLE:</b></font> " Computer Vision, Pattern Recognition, Image Processing and Graphics",<br><font color=green><b>DATES: </b></font> 16 to 19th December', 'Link': 'http://iitmandi.ac.in/main/ncvpripg_17/index.html'},
{'Date': new Date(2017, 11, 21), 'Title': 'A National Workshop on reliability and economic performance of multi-functional microgrids for Indian scenario', 'Link': '#'},


{'Date': new Date(2018, 1, 15), 'Title': 'Classes begin Students report to FA for registration', 'Link': '#'},
{'Date': new Date(2018, 1, 16), 'Title': 'Last date to submit fees', 'Link': '#'},
{'Date': new Date(2018, 1, 23), 'Title': 'Last date to add courses', 'Link': '#'},
{'Date': new Date(2018, 1, 24), 'Title': 'Foundation Day', 'Link': '#'},

{'Date': new Date(2018, 2, 1), 'Title': 'Last Date to drop courses', 'Link': '#'},
{'Date': new Date(2018, 2, 5), 'Title': 'CCM Week', 'Link': '#'},
{'Date': new Date(2018, 2, 10), 'Title': 'Athletics Day', 'Link': '#'},
{'Date': new Date(2018, 2, 13), 'Title': 'Quiz 1', 'Link': '#'},  
{'Date': new Date(2018, 2, 14), 'Title': 'Quiz 2', 'Link': '#'},
{'Date': new Date(2018, 2, 15), 'Title': 'Quiz 3', 'Link': '#'},
{'Date': new Date(2018, 2, 16), 'Title': 'Quiz 4', 'Link': '#'},
{'Date': new Date(2018, 2, 17), 'Title': 'Research Fair', 'Link': '#'},
{'Date': new Date(2018, 2, 19), 'Title': 'Quiz 5', 'Link': '#'},
{'Date': new Date(2018, 2, 20), 'Title': 'Quiz 6', 'Link': '#'},
{'Date': new Date(2018, 2, 21), 'Title': 'Quiz 7', 'Link': '#'},
{'Date': new Date(2018, 2, 22), 'Title': 'Quiz 8', 'Link': '#'},
{'Date': new Date(2018, 2, 24), 'Title': 'Lit. Fest', 'Link': '#'},

{'Date': new Date(2018, 3, 2), 'Title': 'PSCES (Annual Meeting on Physics of Strongly Correlated Electron Systems) during 02-04 April <br> Science Academies Lectures Workshop on the Essence of Partial Differential Equation during 02-04 April 2018, IIT Mandi',},

{'Date': new Date(2018, 3, 7), 'Title': 'Exodia', 'Link': '#'},
{'Date': new Date(2018, 3, 8), 'Title': 'Exodia', 'Link': '#'},
{'Date': new Date(2018, 3, 9), 'Title': 'CCM Week', 'Link': '#'},
{'Date': new Date(2018, 3, 14), 'Title': 'Rann', 'Link': '#'},
{'Date': new Date(2018, 3, 15), 'Title': 'Rann', 'Link': '#'},
{'Date': new Date(2018, 3, 19), 'Title': 'Quiz 1', 'Link': '#'},
{'Date': new Date(2018, 3, 20), 'Title': 'Quiz 2', 'Link': '#'},
{'Date': new Date(2018, 3, 23), 'Title': 'Quiz 3', 'Link': '#'},
{'Date': new Date(2018, 3, 24), 'Title': 'Quiz 4', 'Link': '#'},
{'Date': new Date(2018, 3, 25), 'Title': 'Quiz 5', 'Link': '#'},
{'Date': new Date(2018, 3, 26), 'Title': 'Quiz 6', 'Link': '#'},
{'Date': new Date(2018, 3, 27), 'Title': 'Quiz 7', 'Link': '#'},

{'Date': new Date(2018, 4, 1), 'Title': 'Quiz 8', 'Link': '#'},
{'Date': new Date(2018, 4, 5), 'Title': 'Aagaz', 'Link': '#'},
{'Date': new Date(2018, 4, 6), 'Title': 'Aagaz', 'Link': '#'},
{'Date': new Date(2018, 4, 12), 'Title': 'Exuberance', 'Link': '#'},
{'Date': new Date(2018, 4, 13), 'Title': 'Exuberance', 'Link': '#'},
{'Date': new Date(2018, 4, 14), 'Title': 'TCF Week', 'Link': '#'},
{'Date': new Date(2018, 4, 19), 'Title': 'Aavishkar Open House', 'Link': '#'},
{'Date': new Date(2018, 4, 20), 'Title': 'DP Open House', 'Link': '#'},
{'Date': new Date(2018, 4, 21), 'Title': 'TCF Week', 'Link': '#'},
{'Date': new Date(2018, 4, 26), 'Title': '1st Alumni meet', 'Link': 'http://iitmandi.ac.in/academics/files/alumnimeet_2018.pdf'},
{'Date': new Date(2018, 4, 27), 'Title': '1st Alumni meet', 'Link': 'http://iitmandi.ac.in/academics/files/alumnimeet_2018.pdf'},
{'Date': new Date(2018, 4, 29), 'Title': 'Friday Schedule:Last Day of Teaching', 'Link': '#'},

{'Date': new Date(2018, 5, 1), 'Title': 'End Sem A', 'Link': '#'},
{'Date': new Date(2018, 5, 2), 'Title': 'End Sem B', 'Link': '#'},
{'Date': new Date(2018, 5, 3), 'Title': 'End Sem C', 'Link': '#'},
{'Date': new Date(2018, 5, 4), 'Title': 'End Sem D', 'Link': '#'},
{'Date': new Date(2018, 5, 5), 'Title': 'End Sem E', 'Link': '#'},
{'Date': new Date(2018, 5, 6), 'Title': 'End Sem F', 'Link': '#'},
{'Date': new Date(2018, 5, 7), 'Title': 'End Sem G', 'Link': '#'},
{'Date': new Date(2018, 5, 8), 'Title': 'End Sem H', 'Link': '#'},
{'Date': new Date(2018, 5, 9), 'Title': 'Vacation Begins for students:Make up exam', 'Link': '#'},
{'Date': new Date(2018, 5, 10), 'Title': 'Make up exam', 'Link': '#'},
{'Date': new Date(2018, 5, 12), 'Title': 'Final CCM', 'Link': '#'},
{'Date': new Date(2018, 5, 13), 'Title': 'Grade Submission', 'Link': '#'},
{'Date': new Date(2018, 5, 14), 'Title': 'Vacation begins for faculty', 'Link': '#'},
{'Date': new Date(2018, 5, 18), 'Title': 'Short term Course on Finite Element Method for Engineers and Researchers(FEMER-2018) from 18th to 22nd ', 'Link': 'http://iitmandi.ac.in/stc/FEMER/'},

{'Date': new Date(2018, 6, 25), 'Title': 'Vacation ends for faculty', 'Link': '#'},
{'Date': new Date(2018, 6, 25), 'Title': 'Reporting Day for 1st year B.Tech; Induction program begins', 'Link': '#'},

{'Date': new Date(2018, 7, 6), 'Title': 'Classes begin: Students report to FA for registration', 'Link': '#'},
{'Date': new Date(2018, 7, 7), 'Title': 'Last date to submit fees', 'Link': '#'},
{'Date': new Date(2018, 7, 14), 'Title': 'Last date to add courses', 'Link': '#'},
{'Date': new Date(2018, 7, 18), 'Title': 'Aakarshan', 'Link': '#'},
{'Date': new Date(2018, 7, 20), 'Title': 'Wednesday schedule', 'Link': '#'},
{'Date': new Date(2018, 7, 23), 'Title': 'Last date to drop courses', 'Link': '#'},
{'Date': new Date(2018, 7, 27), 'Title': 'CCM Week', 'Link': '#'},

{'Date': new Date(2018, 8, 1), 'Title': 'Freshers Sport Meet', 'Link': '#'},
{'Date': new Date(2018, 8, 3), 'Title': 'Quiz 1', 'Link': '#'},
{'Date': new Date(2018, 8, 4), 'Title': 'Quiz 2', 'Link': '#'},
{'Date': new Date(2018, 8, 5), 'Title': 'Quiz 3', 'Link': '#'},
{'Date': new Date(2018, 8, 6), 'Title': 'Quiz 4', 'Link': '#'},
{'Date': new Date(2018, 8, 7), 'Title': 'Quiz 5', 'Link': '#'},
{'Date': new Date(2018, 8, 10), 'Title': 'Quiz 6', 'Link': '#'},
{'Date': new Date(2018, 8, 11), 'Title': 'Quiz 7', 'Link': '#'},
{'Date': new Date(2018, 8, 12), 'Title': 'Quiz 8', 'Link': '#'},
{'Date': new Date(2018, 8, 20), 'Title': 'Friday schedule', 'Link': '#'},
{'Date': new Date(2018, 8, 21), 'Title': 'Rann-Neeti', 'Link': '#'},
{'Date': new Date(2018, 8, 22), 'Title': 'Rann-Neeti', 'Link': '#'},
{'Date': new Date(2018, 8, 23), 'Title': 'Rann-Neeti', 'Link': '#'},

{'Date': new Date(2018, 9, 1), 'Title': 'CCM Week', 'Link': '#'},
{'Date': new Date(2018, 9, 11), 'Title': 'Quiz1', 'Link': '#'},
{'Date': new Date(2018, 9, 12), 'Title': 'Quiz2', 'Link': '#'},
{'Date': new Date(2018, 9, 15), 'Title': 'Quiz3', 'Link': '#'},
{'Date': new Date(2018, 9, 16), 'Title': 'Quiz4', 'Link': '#'},
{'Date': new Date(2018, 9, 17), 'Title': 'Quiz5', 'Link': '#'},
{'Date': new Date(2018, 9, 18), 'Title': 'Quiz6', 'Link': '#'},
{'Date': new Date(2018, 9, 22), 'Title': 'Quiz7', 'Link': '#'},
{'Date': new Date(2018, 9, 23), 'Title': 'Quiz8', 'Link': '#'},
{'Date': new Date(2018, 9, 31), 'Title': 'International Workshop on Nano/Micro 2D-3D Fabrication, Manufacturing of Electronic – Biomedical Devices & Applications from 31st Oct. to 2nd Nov. 2018 ', 'Link': 'https://www.iwnebd.com/'},

{'Date': new Date(2018, 10, 3), 'Title': 'Yuvyom', 'Link': '#'},
{'Date': new Date(2018, 10, 4), 'Title': 'Yuvyom', 'Link': '#'},
{'Date': new Date(2018, 10, 5), 'Title': 'TCF Week', 'Link': '#'},
{'Date': new Date(2018, 10, 10), 'Title': 'Utkarsh', 'Link': '#'},
{'Date': new Date(2018, 10, 11), 'Title': 'Utkarsh', 'Link': '#'},
{'Date': new Date(2018, 10, 12), 'Title': 'TCF Week <br> Traning Program- Landslide mitigation & rehabilitation (12th-14th November 2018)', 'Link': '#'},
{'Date': new Date(2018, 10, 19), 'Title': 'Last Day of teaching except for B.Tech 1st year; Wednesday schedule', 'Link': '#'},
{'Date': new Date(2018, 10, 23), 'Title': 'End Sem A', 'Link': '#'},
{'Date': new Date(2018, 10, 24), 'Title': 'End Sem B', 'Link': '#'},
{'Date': new Date(2018, 10, 25), 'Title': 'End Sem C', 'Link': '#'},
{'Date': new Date(2018, 10, 26), 'Title': 'End Sem D<br> HPC- Faculty Development program 2018 (26th-30th November)', 'Link': '#'},
{'Date': new Date(2018, 10, 27), 'Title': 'End Sem E', 'Link': '#'},
{'Date': new Date(2018, 10, 28), 'Title': 'End Sem F', 'Link': '#'},
{'Date': new Date(2018, 10, 29), 'Title': 'End Sem G', 'Link': '#'},
{'Date': new Date(2018, 10, 30), 'Title': 'End Sem H; Last Day of teaching for B.Tech 1st year' , 'Link': '#'},

{'Date': new Date(2018, 11, 1), 'Title': 'Vacation begins for students(except B.Tech 1st year);Make up exam', 'Link': '#'},
{'Date': new Date(2018, 11, 2), 'Title': 'Make up exam', 'Link': '#'},
{'Date': new Date(2018, 11, 3), 'Title': 'Make up exam; End Sem 1 for B.Tech 1st Year', 'Link': '#'},
{'Date': new Date(2018, 11, 4), 'Title': 'End Sem 2 for B.Tech 1st Year', 'Link': '#'},
{'Date': new Date(2018, 11, 5), 'Title': 'Final CCM; End Sem 3 for B.Tech 1st Year', 'Link': '#'},
{'Date': new Date(2018, 11, 6), 'Title': 'Grade Submission; End Sem 4 for B.Tech 1st Year', 'Link': '#'},
{'Date': new Date(2018, 11, 7), 'Title': 'End Sem 5 for B.Tech 1st Year; Vacation begins for faculty', 'Link': '#'},
{'Date': new Date(2018, 11, 10), 'Title': 'CCM and grade submission for B.Tech 1st year', 'Link': '#'},


{'Date': new Date(2019, 1, 11), 'Title': 'National workshop on Water Filteration Technique based on Solar Energy 11-13th February 2019', 'Link': '#'},
{'Date': new Date(2019, 1, 12), 'Title': 'National workshop on Water Filteration Technique based on Solar Energy 11-13th February 2019', 'Link': '#'},
{'Date': new Date(2019, 1, 13), 'Title': 'National workshop on Water Filteration Technique based on Solar Energy 11-13th February 2019', 'Link': '#'},
{'Date': new Date(2019, 1, 18), 'Title': 'Classes brgin:Students report to FA for registration', 'Link': '#'},
{'Date': new Date(2019, 1, 19), 'Title': 'Last date to submit fees', 'Link': '#'},

{'Date': new Date(2019, 2, 2), 'Title': 'Litfest', 'Link': '#'},
{'Date': new Date(2019, 2, 3), 'Title': 'Litfest', 'Link': '#'},
{'Date': new Date(2019, 2, 9), 'Title': 'Utkarsh', 'Link': '#'},
{'Date': new Date(2019, 2, 10), 'Title': 'Utkarsh', 'Link': '#'},
{'Date': new Date(2019, 2, 5), 'Title': 'Last date to add/drop courses', 'Link': '#'},
{'Date': new Date(2019, 2, 11), 'Title': 'CCM Week', 'Link': '#'},
{'Date': new Date(2019, 2, 18), 'Title': 'Quiz 1', 'Link': '#'},
{'Date': new Date(2019, 2, 19), 'Title': 'Quiz 2', 'Link': '#'},
{'Date': new Date(2019, 2, 21), 'Title': 'Quiz 3', 'Link': '#'},
{'Date': new Date(2019, 2, 22), 'Title': 'Quiz 4', 'Link': '#'},
{'Date': new Date(2019, 2, 25), 'Title': 'Quiz 5', 'Link': '#'},
{'Date': new Date(2019, 2, 26), 'Title': 'Quiz 6', 'Link': '#'},
{'Date': new Date(2019, 2, 27), 'Title': 'Quiz 7', 'Link': '#'},
{'Date': new Date(2019, 2, 28), 'Title': 'Quiz 8', 'Link': '#'},

{'Date': new Date(2019, 3, 15), 'Title': 'CCM Week', 'Link': '#'},
{'Date': new Date(2019, 3, 19), 'Title': 'Exodia', 'Link': '#'},
{'Date': new Date(2019, 3, 20), 'Title': 'Exodia', 'Link': '#'},
{'Date': new Date(2019, 3, 21), 'Title': 'Exodia', 'Link': '#'},
{'Date': new Date(2019, 3, 25), 'Title': 'Quiz 1', 'Link': '#'},
{'Date': new Date(2019, 3, 26), 'Title': 'Quiz 2', 'Link': '#'},
{'Date': new Date(2019, 3, 29), 'Title': 'Quiz 3', 'Link': '#'},
{'Date': new Date(2019, 3, 30), 'Title': 'Quiz 4', 'Link': '#'},

{'Date': new Date(2019, 4, 1), 'Title': 'Quiz 5', 'Link': '#'},
{'Date': new Date(2019, 4, 2), 'Title': 'Quiz 6', 'Link': '#'},
{'Date': new Date(2019, 4, 3), 'Title': 'Quiz 7', 'Link': '#'},
{'Date': new Date(2019, 4, 6), 'Title': 'Quiz 8', 'Link': '#'},
{'Date': new Date(2019, 4, 11), 'Title': 'Aagaaz', 'Link': '#'},
{'Date': new Date(2019, 4, 12), 'Title': 'Aagaaz', 'Link': '#'},
{'Date': new Date(2019, 4, 19), 'Title': 'Exuberance', 'Link': '#'},
{'Date': new Date(2019, 4, 20), 'Title': 'TCF Week', 'Link': '#'},
{'Date': new Date(2019, 4, 27), 'Title': 'TCF Week', 'Link': '#'},
{'Date': new Date(2019, 4, 28), 'Title': 'Wednesday schedule', 'Link': '#'},
{'Date': new Date(2019, 4, 30), 'Title': 'Friday Schedule; Last day of teaching', 'Link': '#'},

{'Date': new Date(2019, 5, 2), 'Title': 'End Sem A', 'Link': '#'},
{'Date': new Date(2019, 5, 3), 'Title': 'End Sem B', 'Link': '#'},
{'Date': new Date(2019, 5, 4), 'Title': 'End Sem C', 'Link': '#'},
{'Date': new Date(2019, 5, 6), 'Title': 'End Sem D', 'Link': '#'},
{'Date': new Date(2019, 5, 7), 'Title': 'End Sem E', 'Link': '#'},
{'Date': new Date(2019, 5, 8), 'Title': 'End Sem F', 'Link': '#'},
{'Date': new Date(2019, 5, 9), 'Title': 'End Sem G', 'Link': '#'},
{'Date': new Date(2019, 5, 10), 'Title': 'End Sem H', 'Link': '#'},
{'Date': new Date(2019, 5, 11), 'Title': 'Vacation begins for students; Makeup Exam', 'Link': '#'},
{'Date': new Date(2019, 5, 12), 'Title': 'Makeup Exam', 'Link': '#'},
{'Date': new Date(2019, 5, 14), 'Title': 'Final CCM', 'Link': '#'},
{'Date': new Date(2019, 5, 15), 'Title': 'Grade Submission', 'Link': '#'},
{'Date': new Date(2019, 5, 16), 'Title': 'Vacation begins for faculty', 'Link': '#'},

{'Date': new Date(2019, 6, 24), 'Title': 'Vacation ends for faculty', 'Link': '#'},
{'Date': new Date(2019, 6, 25), 'Title': 'Reporting day for 1st year B.Tech; Induction program begins', 'Link': '#'},

{'Date': new Date(2019, 7, 7), 'Title': 'Classes begin: Students report to FA for registration', 'Link': '#'},
{'Date': new Date(2019, 7, 8), 'Title': 'Last date to submit fees', 'Link': '#'},
{'Date': new Date(2019, 7, 17), 'Title': 'Aakarshan', 'Link': '#'},
{'Date': new Date(2019, 7, 23), 'Title': 'Last date to add/drop courses', 'Link': '#'},
{'Date': new Date(2019, 7, 25), 'Title': 'Aagaman', 'Link': '#'},
{'Date': new Date(2019, 7, 26), 'Title': 'CCM Week', 'Link': '#'},
{'Date': new Date(2019, 7, 29), 'Title': 'Tuesday Schedule', 'Link': '#'},

{'Date': new Date(2019, 8, 1), 'Title': 'Freshers Sports Meet', 'Link': '#'},
{'Date': new Date(2019, 8, 4), 'Title': 'Quiz I', 'Link': '#'},
{'Date': new Date(2019, 8, 5), 'Title': 'Quiz I', 'Link': '#'},
{'Date': new Date(2019, 8, 6), 'Title': 'Quiz I', 'Link': '#'},
{'Date': new Date(2019, 8, 9), 'Title': 'Quiz I', 'Link': '#'},
{'Date': new Date(2019, 8, 11), 'Title': 'Quiz I', 'Link': '#'},
{'Date': new Date(2019, 8, 12), 'Title': 'Quiz I', 'Link': '#'},
{'Date': new Date(2019, 8, 13), 'Title': 'Quiz I', 'Link': '#'},
{'Date': new Date(2019, 8, 16), 'Title': 'Quiz I', 'Link': '#'},
{'Date': new Date(2019, 8, 23), 'Title': 'Workshop on Landslide mitigation & DPR preparation from 23-27 Sept. 2091', 'Link': '#'},
{'Date': new Date(2019, 8, 24), 'Title': 'Workshop on Landslide mitigation & DPR preparation from 23-27 Sept. 2091', 'Link': '#'},
{'Date': new Date(2019, 8, 25), 'Title': 'Workshop on Landslide mitigation & DPR preparation from 23-27 Sept. 2091', 'Link': '#'},
{'Date': new Date(2019, 8, 26), 'Title': 'Workshop on Landslide mitigation & DPR preparation from 23-27 Sept. 2091', 'Link': '#'},
{'Date': new Date(2019, 8, 27), 'Title': 'Workshop on Landslide mitigation & DPR preparation from 23-27 Sept. 2091', 'Link': '#'},
{'Date': new Date(2019, 8, 28), 'Title': 'Rann Neeti', 'Link': '#'},
{'Date': new Date(2019, 8, 29), 'Title': 'Rann Neeti', 'Link': '#'},

{'Date': new Date(2019, 9, 3), 'Title': 'CCM Week', 'Link': '#'},
{'Date': new Date(2019, 9, 15), 'Title': 'Quiz II', 'Link': '#'},
{'Date': new Date(2019, 9, 16), 'Title': 'Quiz II', 'Link': '#'},
{'Date': new Date(2019, 9, 17), 'Title': 'Quiz II', 'Link': '#'},
{'Date': new Date(2019, 9, 18), 'Title': 'Quiz II', 'Link': '#'},
{'Date': new Date(2019, 9, 21), 'Title': 'Quiz II', 'Link': '#'},
{'Date': new Date(2019, 9, 22), 'Title': 'Quiz II', 'Link': '#'},
{'Date': new Date(2019, 9, 23), 'Title': 'Quiz II', 'Link': '#'},
{'Date': new Date(2019, 9, 24), 'Title': 'Quiz II', 'Link': '#'},

{'Date': new Date(2019, 10, 2), 'Title': 'Utkarsh', 'Link': '#'},
{'Date': new Date(2019, 10, 3), 'Title': 'Utkarsh', 'Link': '#'},
{'Date': new Date(2019, 10, 4), 'Title': 'TCF Week', 'Link': '#'},
{'Date': new Date(2019, 10, 15), 'Title': 'Tuesday Schedule', 'Link': '#'},
{'Date': new Date(2019, 10, 20), 'Title': 'Thursday Schedule (Last day of teaching)', 'Link': '#'},
{'Date': new Date(2019, 10, 23), 'Title': 'End Sem A', 'Link': '#'},
{'Date': new Date(2019, 10, 24), 'Title': 'End Sem B', 'Link': '#'},
{'Date': new Date(2019, 10, 25), 'Title': 'End Sem C', 'Link': '#'},
{'Date': new Date(2019, 10, 26), 'Title': 'End Sem D', 'Link': '#'},
{'Date': new Date(2019, 10, 27), 'Title': 'End Sem E', 'Link': '#'},
{'Date': new Date(2019, 10, 28), 'Title': 'End Sem F', 'Link': '#'},
{'Date': new Date(2019, 10, 29), 'Title': 'End Sem G', 'Link': '#'},
{'Date': new Date(2019, 10, 30), 'Title': 'End Sem H', 'Link': '#'},

{'Date': new Date(2019, 11, 1), 'Title': 'Vacation Begins for Students (Except B.Tech 1st year)', 'Link': '#'},
{'Date': new Date(2019, 11, 2), 'Title': 'Make-up exam', 'Link': '#'},
{'Date': new Date(2019, 11, 3), 'Title': 'End Sem B.Tech 1st year starts', 'Link': '#'},
{'Date': new Date(2019, 11, 4), 'Title': 'End Sem B.Tech 1st year', 'Link': '#'},
{'Date': new Date(2019, 11, 5), 'Title': 'Final CCM;End Sem B.Tech 1st year; Final CCM', 'Link': '#'},
{'Date': new Date(2019, 11, 6), 'Title': 'Grade Submission; End Sem B.Tech 1st year', 'Link': '#'},
{'Date': new Date(2019, 11, 7), 'Title': 'End Sem B.Tech 1st year (Vacation begins for faculty)', 'Link': '#'},
{'Date': new Date(2019, 11, 10), 'Title': 'CCM and Grade Submission for B.Tech 1st year', 'Link': '#'},


{'Date': new Date(2019, 0, 21), 'Title': 'Earthquake risk mitigation  on 21st to 23rd January 2019', 'Link': '#'},
{'Date': new Date(2019, 0, 22), 'Title': 'Earthquake risk mitigation  on 21st to 23rd January 2019', 'Link': '#'},
{'Date': new Date(2019, 0, 23), 'Title': 'Earthquake risk mitigation  on 21st to 23rd January 2019', 'Link': '#'},
{'Date': new Date(2019, 3, 18), 'Title': 'Climate changes and extreme events in himalaya  on 18th to 20th April 2019', 'Link': '#'},
{'Date': new Date(2019, 3, 19), 'Title': 'Climate changes and extreme events in himalaya  on 18th to 20th April 2019', 'Link': '#'},
{'Date': new Date(2019, 3, 20), 'Title': 'Climate changes and extreme events in himalaya  on 18th to 20th April 2019', 'Link': '#'},
{'Date': new Date(2019, 5, 17), 'Title': 'ICDECP19 from 17th-19th June 2019', 'Link': 'http://iitmandi.ac.in/icdecp19/'},

{'Date': new Date(2019, 5, 24), 'Title': 'The 64th congress of Indian society of theoretical and mechanics 24-26th June 2019', 'Link': '#'},
{'Date': new Date(2019, 5, 25), 'Title': 'The 64th congress of Indian society of theoretical and mechanics 24-26th June 2019', 'Link': '#'},
{'Date': new Date(2019, 5, 26), 'Title': 'The 64th congress of Indian society of theoretical and mechanics 24-26th June 2019', 'Link': '#'},
{'Date': new Date(2019, 10, 10), 'Title': 'IEEE PIICON 2019 9th IEEE Power India International Conference', 'Link': '#'},
{'Date': new Date(2019, 10, 11), 'Title': 'IEEE PIICON 2019 9th IEEE Power India International Conference, TCF Week', 'Link': '#'},
{'Date': new Date(2019, 10, 12), 'Title': 'IEEE PIICON 2019 9th IEEE Power India International Conference', 'Link': '#'},

{'Date': new Date(2020, 1, 9), 'Title': 'Vacation concludes for faculty', 'Link': '#'},
{'Date': new Date(2020, 1, 17), 'Title': 'Classes begin:Students report to FA for registration', 'Link': '#'},
{'Date': new Date(2020, 1, 18), 'Title': 'Last date to submit fees', 'Link': '#'},
{'Date': new Date(2020, 1, 24), 'Title': 'Foundation Day', 'Link': '#'},

{'Date': new Date(2020, 2, 2), 'Title': 'Last date to add/drop courses', 'Link': '#'},
{'Date': new Date(2020, 2, 7), 'Title': 'Aagaz', 'Link': '#'},
{'Date': new Date(2020, 2, 8), 'Title': 'Aagaz', 'Link': '#'},
{'Date': new Date(2020, 2, 16), 'Title': 'Quiz 1, 2nd Winter School Cognitive Modelling at IIT Mandi from March 16-21, 2020', 'Link': '#'},
{'Date': new Date(2020, 2, 17), 'Title': 'Quiz 1', 'Link': '#'},
{'Date': new Date(2020, 2, 18), 'Title': 'Quiz 1', 'Link': '#'},
{'Date': new Date(2020, 2, 19), 'Title': 'Quiz 1, FluxMetSys 2020 - MHRD SPARC Indo-UK Workshop from March 19-22, 2020 ', 'Link': '#'},
{'Date': new Date(2020, 2, 20), 'Title': 'Quiz 1', 'Link': '#'},
{'Date': new Date(2020, 2, 23), 'Title': 'Quiz 1', 'Link': '#'},
{'Date': new Date(2020, 2, 24), 'Title': 'Quiz 1', 'Link': '#'},
{'Date': new Date(2020, 2, 25), 'Title': 'Quiz 1', 'Link': '#'},
{'Date': new Date(2020, 2, 30), 'Title': 'Announcement of comprehensive exam result', 'Link': '#'},

{'Date': new Date(2020, 3, 4), 'Title': 'Exodia', 'Link': '#'},
{'Date': new Date(2020, 3, 5), 'Title': 'Exodia', 'Link': '#'},
{'Date': new Date(2020, 3, 7), 'Title': 'CCM Week', 'Link': '#'},
{'Date': new Date(2020, 3, 11), 'Title': 'Anusandhan', 'Link': '#'},
{'Date': new Date(2020, 3, 12), 'Title': 'Anusandhan', 'Link': '#'},
{'Date': new Date(2020, 3, 22), 'Title': 'Quiz 2', 'Link': '#'},
{'Date': new Date(2020, 3, 23), 'Title': 'Quiz 2', 'Link': '#'},
{'Date': new Date(2020, 3, 24), 'Title': 'Quiz 2', 'Link': '#'},
{'Date': new Date(2020, 3, 27), 'Title': 'Quiz 2', 'Link': '#'},
{'Date': new Date(2020, 3, 28), 'Title': 'Quiz 2', 'Link': '#'},
{'Date': new Date(2020, 3, 29), 'Title': 'Quiz 2', 'Link': '#'},
{'Date': new Date(2020, 3, 30), 'Title': 'Quiz 2', 'Link': '#'},

{'Date': new Date(2020, 4, 1), 'Title': 'Quiz 2', 'Link': '#'},
{'Date': new Date(2020, 4, 5), 'Title': 'Friday Schedule', 'Link': '#'},
{'Date': new Date(2020, 4, 17), 'Title': 'Exuberance', 'Link': '#'},
{'Date': new Date(2020, 4, 18), 'Title': 'TCF Week', 'Link': '#'},
{'Date': new Date(2020, 4, 24), 'Title': 'Hostel GC closing ceremony', 'Link': '#'},
{'Date': new Date(2020, 4, 26), 'Title': 'TCF Week', 'Link': '#'},
{'Date': new Date(2020, 4, 27), 'Title': 'Monday Schedule', 'Link': '#'},
{'Date': new Date(2020, 4, 30), 'Title': 'Monday Schedule/Last day of teaching', 'Link': '#'},

{'Date': new Date(2020, 5, 2), 'Title': 'End Sem A', 'Link': '#'},
{'Date': new Date(2020, 5, 3), 'Title': 'End Sem B', 'Link': '#'},
{'Date': new Date(2020, 5, 4), 'Title': 'End Sem C', 'Link': '#'},
{'Date': new Date(2020, 5, 5), 'Title': 'End Sem D', 'Link': '#'},
{'Date': new Date(2020, 5, 6), 'Title': 'End Sem E', 'Link': '#'},
{'Date': new Date(2020, 5, 7), 'Title': 'End Sem F', 'Link': '#'},
{'Date': new Date(2020, 5, 8), 'Title': 'End Sem G', 'Link': '#'},
{'Date': new Date(2020, 5, 9), 'Title': 'End Sem H', 'Link': '#'},
{'Date': new Date(2020, 5, 10), 'Title': 'Vacation begins for students/Makeup exam', 'Link': '#'},
{'Date': new Date(2020, 5, 11), 'Title': 'Makeup exam', 'Link': '#'},
{'Date': new Date(2020, 5, 13), 'Title': 'Final CCM', 'Link': '#'},
{'Date': new Date(2020, 5, 15), 'Title': 'Grade submission', 'Link': '#'},
{'Date': new Date(2020, 5, 16), 'Title': 'Vacation begins for faculty', 'Link': '#'},

{'Date': new Date(2020, 6, 19), 'Title': 'Vacation concludes for faculty', 'Link': '#'},
{'Date': new Date(2020, 6, 25), 'Title': 'Reporting day for 1st year B.Tech', 'Link': '#'},
{'Date': new Date(2020, 6, 26), 'Title': 'Orientation progran for 1st year B.Tech', 'Link': '#'},
{'Date': new Date(2020, 6, 27), 'Title': 'Five week induction program begins', 'Link': '#'},




];
var settings = {};
var element = document.getElementById('caleandar');
caleandar(element, events, settings);
